export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_LOGIN_ERRORS = "GET_LOGIN_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// CATERGORY MODULE TYPES
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const EDIT_CATEGORY = "EDIT_CATEGORY";